/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package binarysystem;

import javax.swing.JPanel;

/**
 *
 * @author Zerotension
 */
public class BaseGUI extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public BaseHandler m_BaseHandler;
    
    public BaseGUI() {
        initComponents();
        m_BaseHandler = new BaseHandler(this);
    }
   
    public JPanel getGrid() {
        return grid1;
    }
    
    public boolean isInitiator() {
        return rInitiator.getSelectedObjects() != null;
    }
    
    public boolean isRepeater() {
        return rRepeater.getSelectedObjects() != null;
    }
    
    public boolean isInverter() {
        return rInverter.getSelectedObjects() != null;
    }
    
    public boolean isConnector() {
        return rConnector.getSelectedObjects() != null;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        rConnector = new javax.swing.JRadioButton();
        rInverter = new javax.swing.JRadioButton();
        rRepeater = new javax.swing.JRadioButton();
        rInitiator = new javax.swing.JRadioButton();
        grid1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Binary System");

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        rConnector.setBackground(new java.awt.Color(153, 153, 153));
        buttonGroup1.add(rConnector);
        rConnector.setText("Connector");
        rConnector.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rConnectorStateChanged(evt);
            }
        });

        rInverter.setBackground(new java.awt.Color(153, 153, 153));
        buttonGroup1.add(rInverter);
        rInverter.setText("Inverter");

        rRepeater.setBackground(new java.awt.Color(153, 153, 153));
        buttonGroup1.add(rRepeater);
        rRepeater.setText("Repeater");

        rInitiator.setBackground(new java.awt.Color(153, 153, 153));
        buttonGroup1.add(rInitiator);
        rInitiator.setText("Initiator");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(rConnector)
                .addGap(2, 2, 2)
                .addComponent(rInverter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rRepeater)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rInitiator)
                .addContainerGap(561, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rConnector)
                    .addComponent(rInverter)
                    .addComponent(rRepeater)
                    .addComponent(rInitiator))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        grid1.setBackground(new java.awt.Color(153, 153, 153));
        grid1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grid1MouseClicked(evt);
            }
        });
        grid1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                grid1MouseMoved(evt);
            }
        });

        javax.swing.GroupLayout grid1Layout = new javax.swing.GroupLayout(grid1);
        grid1.setLayout(grid1Layout);
        grid1Layout.setHorizontalGroup(
            grid1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        grid1Layout.setVerticalGroup(
            grid1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 551, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(grid1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(grid1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void grid1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grid1MouseClicked
        m_BaseHandler.grid_onMouseClick(evt);
    }//GEN-LAST:event_grid1MouseClicked

    private void grid1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grid1MouseMoved
        m_BaseHandler.grid_onMouseMove(evt);
    }//GEN-LAST:event_grid1MouseMoved

    private void rConnectorStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rConnectorStateChanged
        if(isConnector()) m_BaseHandler.m_SelectedNode = null;
    }//GEN-LAST:event_rConnectorStateChanged
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BaseGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BaseGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BaseGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BaseGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                //new BinarySystemGUI().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel grid1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton rConnector;
    private javax.swing.JRadioButton rInitiator;
    private javax.swing.JRadioButton rInverter;
    private javax.swing.JRadioButton rRepeater;
    // End of variables declaration//GEN-END:variables
}
